export const SET_TYPING_VALUE = "SET_TYPING_VALUE";
export const SET_TYPING_SUGGESTIONS = "SET_TYPING_SUGGESTIONS";
export const SET_COUNTRY_REPORT = "SET_COUNTRY_REPORT";
export const SET_COUNTRY_REPORTS = "SET_COUNTRY_REPORTS";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const SET_COUNTRY_TWEETS = "SET_COUNTRY_TWEETS";
